- name: Erlang version
  set_fact:
    elixir_version: 1.18.3-otp-25
    erlang_version: 25.3.2.18

# - name: Install erlang dependencies
#   become: true
#   ansible.builtin.package:
#     state: present
#     name:
#       - libssl-dev
#       - build-essential
#       - automake
#       - autoconf
#       - m4
#       - libncurses-dev
#       - libwxgtk3.2-dev
#       - libwxgtk-webview3.2-dev
#       - libgl1-mesa-dev
#       - libglu1-mesa-dev
#       - libpng-dev
#       - libssh-dev
#       - unixodbc-dev
#       - xsltproc
#       - fop
#       - libxml2-utils
#       - ament-cmake-xmllint
#       - inotify-tools
#       - openjdk-17-jdk
#   when: ansible_os_family == 'Debian'
#
#
# - name: Install erlang dependencies
#   become: true
#   ansible.builtin.package:
#     state: present
#     name:
#       - libxslt
#       - fop
#       - inotify-tools
#       - glu
#       - mesa
#       - wxwidgets-gtk3
#       - libpng
#       - libssh
#       - unixodbc
#       - ncurses
#   when: ansible_os_family == 'Archlinux'

#
# # Installing erlang
# - name: Add erlang plugin to asdf
#   command: "asdf plugin add erlang"
#
#
# - name: Install erlang {{erlang_version}} with asdf
#   command: "asdf install erlang {{ erlang_version}}"
#   when: ansible_os_family == 'Debian'
#
#
# - name: Install erlang {{erlang_version}} with asdf
# # export KERL_CONFIGURE_OPTIONS="--without-javac --with-odbc=/var/lib/pacman/local/unixodbc-$(pacman -Q unixodbc | cut -d' ' -f2)"
#   command: >
#     asdf install erlang {{ erlang_version}}
#   when: ansible_os_family == 'Archlinux'
#
#
# - name: Set global version for golang to {{erlang_version}}
#   command: "asdf global erlang {{erlang_version}}"
#
#
  # Installing elixir
