- name: Install ocaml dependencies
  become: true
  ansible.builtin.package:
    state: present
    name:
      - bubblewrap
      - rsync
      - opam
  when: ansible_os_family == 'Archlinux'

- name: Initialize ocaml package manager -> opam
  command: "opam init"

- name: Install ocaml tools
  command: "opam install ocaml-lsp-server odoc ocamlformat utop"
