- name: Install ocaml dependencies
  become: true
  ansible.builtin.package:
    state: present
    name:
      - bubblewrap
      - rsync
  when: ansible_os_family == 'Archlinux'

- name: Added Ocaml toolchain
  shell: >
    bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"

- name: Initialize ocaml package manager -> opam
  command: "opam init"

- name: Install ocaml tools
  command: "opam install ocaml-lsp-server odoc ocamlformat utop"
