-- local jdtls = require('mason-registry').get_package('jdtls')
--
-- local config = {
--     cmd = { jdtls:get_install_path() .. "/jdtls" },
--     root_dir = vim.fs.dirname(vim.fs.find({ 'gradlew', '.git', 'mvnw' }, { upward = true })[1]),
-- }
--
-- require('jdtls').start_or_attach(config)
