- name: Install Common Tools
  become: true
  ansible.builtin.package:
    state: present
    name:
      - git
      - ripgrep
      - exa
      - fzf
      - zoxide
      - bat
      - unzip
      - bpytop
      - wget
      - curl
      - jq
      - protobuf
      - tldr
      - luarocks

- name: Install Debian Common tools
  become: true
  ansible.builtin.package:
    state: present
    name:
      - "fd-find"
      - "build-essential"
  when: ansible_os_family == 'Debian'

- name: Install Arch Common tools
  become: true
  ansible.builtin.package:
    state: present
    name:
      - "extra/fd"
      - "inetutils"
      - "core/less"
      - "openssh"
      - "mhash"
      - "python-pip"
      - "base-devel"
      - "reflector"
      - "clang"
      - "llvm"
  when: ansible_os_family == 'Archlinux'


- name: Optmimize Arch Pacman
  become: true
  shell: |
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    reflector --save /etc/pacman.d/mirrorlist --protocol https --sort rate --latest 10
  args:
    executable: /bin/bash
  when: ansible_os_family == 'Archlinux'
