- name: Install Common Tools
  become: true
  ansible.builtin.package:
    state: present
    name:
      - git
      - ripgrep
      - exa
      - fzf
      - zoxide
      - bat
      - unzip
      - bpytop
      - wget
      - curl
      - jq
      - protobuf

- name: Install Debian Common tools
  become: true
  ansible.builtin.package:
    state: present
    name:
      - "fd-find"
      - "build-essential"
  when: ansible_os_family == 'Debian'

- name: Install Arch Common tools
  become: true
  ansible.builtin.package:
    state: present
    name:
      - "extra/fd"
      - "inetutils"
      - "core/less"
      - "openssh"
      - "mhash"
      - "python-pip"

  when: ansible_os_family == 'Archlinux'
