- name: Neovim version
  set_fact:
    neovim_version: "nightly"
    # neovim_version: "v0.10.0"

- name: Install neovim binary dependencies
  become: true
  ansible.builtin.package:
    state: present
    name:
      - "tree-sitter"
      - "tree-sitter-cli"
      - "julia"
      - "python-pynvim"
  when: ansible_os_family == 'Archlinux'

- name: Node neovim package
  shell: >
    npm install -g neovim

- name: Neovim clean previous install
  become: true
  shell: |
    rm /usr/local/bin/nvim
    rm -rf /opt/nvim-linux64
  args:
    executable: /bin/bash
    chdir: "/opt"

- name: "Install neovim"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.tar.gz"
    creates: /opt/nvim-linux64
    dest: /opt/
    remote_src: yes

- name: "Link neovim executable"
  become: true
  ansible.builtin.file:
    src: "/opt/nvim-linux64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
    force: true

- name: "Link neovim configuration"
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
