return {}
-- return {
-- 	{
-- 		"mfussenegger/nvim-dap",
-- 	},
-- 	{
-- 		"rcarriga/nvim-dap-ui",
-- 		dependencies = { "mfussenegger/nvim-dap" },
-- 	},
-- 	{
-- 		"theHamsta/nvim-dap-virtual-text"
-- 	},
-- 	{
--
-- 		"mfussenegger/nvim-dap-python",
-- 		ft = "python",
-- 		dependencies = {
-- 			"mfussenegger/nvim-dap",
-- 		},
-- 		config = function()
-- 			local path = "~/.local/share/nvim/mason/packages/debugpy/venv/bin/python"
-- 			require('dap-python').setup(path)
-- 		end
-- 	},
-- 	{
-- 		"leoluz/nvim-dap-go",
-- 		ft = "go",
--
-- 		dependencies = {
-- 			"mfussenegger/nvim-dap",
-- 		},
-- 	},
-- }
-- local dap = require("dap")
-- local dapui = require("dapui")
-- require('nvim-dap-virtual-text').setup()
--
-- dapui.setup()
--
-- dap.listeners.after.event_initialized["dapui_config"] = function()
-- 	dapui.open()
-- end
--
-- dap.listeners.before.event_terminated["dapui_config"] = function()
-- 	dapui.close()
-- end
--
--
-- dap.listeners.before.event_exited["dapui_config"] = function()
-- 	dapui.close()
-- end
--
-- vim.keymap.set("n", "<leader>tb", vim.cmd.DapToggleBreakpoint)
-- vim.keymap.set("n", "<leader>tB", ":lua require('dap').set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>")
-- vim.keymap.set("n", "<leader>ro", ":lua require('dap').repl.open()<CR>")
-- vim.keymap.set("n", "<F6>", vim.cmd.DapStepOver)
-- vim.keymap.set("n", "<F7>", vim.cmd.DapStepInto)
-- vim.keymap.set("n", "<F8>", vim.cmd.DapStepOut)
-- vim.keymap.set("n", "<F9>", vim.cmd.DapContinue)
-- vim.keymap.set("n", "<F10>", vim.cmd.DapTerminate)
-- require("dap-go").setup({
--     ft = "go"
-- })
--
-- vim.keymap.set("n", "<leader>tg", ":lua require('dap-go').debug_test()<CR>")
--
